version: '3.7'
services:
  chat-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/app:ro
      - /app/node_modules
    env_file:
      - .env
